<a href="https://colab.research.google.com/github/tanishachouhan019/Numpy/blob/main/Class1file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Using NumPy**

Once you've installed NumPy you can import it as a library:

In [ ]:
pip install numpy

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [ ]:
import numpy as np
l = [10,20,30,40,50]  #1D array
array = np.array(l)
print(array)

[10 20 30 40 50]


Lets create a matrix using list

In [ ]:
a =[[1,2,3],[4,5,6],[7,8,9]]
matrix = np.array(a)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Now lets see how matlix looks like using numpy arrays

In [ ]:
import numpy as np
a =[[1,2,3],[4,5,6],[7,8,9]]
matrix = np.array(a)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

there are lots of build in methods to create an array lets create some and see

np.zeros(), np.ones(), np.full()

np.arange(), np.linspace()

np.eye()

In [ ]:
#np.zeros() for 1D
np.zeros(4)

array([0., 0., 0., 0.])

In [ ]:
#np.zeros() for matrix
#rows and columns
np.zeros([3,4])  #rpes and column

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#np.ones()
np.ones(4)



array([1., 1., 1., 1.])

In [ ]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#np.full()
np.full(5,7)

array([7, 7, 7, 7, 7])

In [ ]:
np.full([3,3],7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [ ]:
#np.arange()  #only 1D created
arr = np.arange(0,10,2)
arr

array([0, 2, 4, 6, 8])

In [ ]:
#np.linspace()  #start=0 ,stop=1, value=5
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
#np.eye()  #identity matrix
np.eye(4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#np.random.rand()  #rows and columns
np.random.rand(2,3)

array([[0.0464286 , 0.56779923, 0.21539455],
       [0.24278563, 0.34597147, 0.52178425]])

In [ ]:
#np.random.randint(start,stop.(rows,column))
np.random.randint(1,20,(3,3))

#randint -> 1 se 20 ke beech ki random values se matrix create karega

array([[16,  5, 16],
       [10,  7,  1],
       [12,  3,  5]])

arange → step-based values

linspace → fixed number of values

eye → identity matrix

rand → random floats (0–1)

randint → random integers in a range

randn → random values from bell curve distribution

In [ ]:
import numpy as np

print(np.arange(1,11))
print(np.linspace(0,10,5))
print(np.eye(3))
print(np.random.rand(2,2))
print(np.random.randint(1,100,5))
print(np.random.randn(5))

[ 1  2  3  4  5  6  7  8  9 10]
[ 0.   2.5  5.   7.5 10. ]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.79422347 0.1346937 ]
 [0.96155565 0.0305217 ]]
[21 13 46 79 18]
[-0.07798862 -1.52826979  1.71306243 -0.2929798   0.91830829]
